name: chocolatine

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: check .o
        run: |
          git rm -r --cached "*.o"
          git add .
          git commit -m "Supprimer les fichiers .o"
          git push --force

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
