name: chocolatine

on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'

env:
  MIRROR_URL: "https://github.com/louthomas94/choco.git"
  EXECUTABLES: "bsq"

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    needs: []
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check coding style
        run: |
          docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" ghcr.io/epitech/coding-style-checker:latest check.sh $(pwd) $(pwd)

  check_program_compilation:
    runs-on: ubuntu-latest
    needs: [check_coding_style]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Make
        run: make
        timeout-minutes: 2
      - name: Make clean
        run: make clean
      - name: Check executables
        run: |
          for executable in $(echo $EXECUTABLES | tr "," " "); do
            if [ ! -x "$executable" ]; then
              echo "Error: $executable is missing or not executable"
              exit 1
            fi
          done
          
  run_tests:
    runs-on: ubuntu-latest
    needs: [check_program_compilation]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: make tests_run
        timeout-minutes: 2

  push_to_mirror:
    runs-on: ubuntu-latest
    needs: [run_tests]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Push to mirror
        env:
          GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
        run: |
          git remote add mirror $MIRROR_URL
          git push --mirror mirror
